display: 10
snapshot: 1000
summary: 100
n_hidden: 2048
n_input: 2048
n_output: 2048
gama: 1.0
lambda1: 0.1 # 0.1 0.2 0.3 0.4
lambda2: 0.1 # 0 0.05 0.1 0.15 0.2
K: 3
seed: 2017
learning_rate: 0.0001
time_steps: 10
batch_size: 4
n_iter: 20000
train_videos_txt: txt/{}_feature_train.txt
test_videos_txt: txt/{}_feature_test.txt
train_feature_path: /home/luowx/datasets/anomaly_detection/{}/training/224/features/twostream_{}/
test_feature_path: /home/luowx/datasets/anomaly_detection/{}/testing/224/features/twostream_{}/motion
dataset: avenue
twostream_model: res152_7x7
save_results_path: results/ad
ckpt_path: ckpt/ad
log_path: log/ad
prefix: info_{}_{}_{}_K_{}_n_hidden_{}_lam1_{}_lam2_{}_T_{} # dataset/twostream_model/model_type/K/n_hidden/lam1/lam2/T
test_loop: 20000
scales:
  - 1
  - 2
  - 4
feature_size: 7.0
model_type: AE
weight_decay: 0.0
gpu: !!str 0
